//
// Milkyway Hierarchical Verilog Dump:
// Generated on 05/08/2017 at 14:05:08
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :aludec_LIB
// Cell Name    :aludec
// Hierarchy delimiter:'/'
// Write Command : write_verilog aludec.pnr.v
//


module aludec (funct , aluop , alucontrol );
input  [5:0] funct ;
input  [1:0] aluop ;
output [6:0] alucontrol ;



INVX2 U8 (.A ( funct[3] ) , .Y ( n5 ) ) ;
INVX2 U7 (.A ( n15 ) , .Y ( n4 ) ) ;
INVX2 U6 (.A ( aluop[1] ) , .Y ( n3 ) ) ;
INVX2 U5 (.A ( alucontrol[1] ) , .Y ( n2 ) ) ;
INVX2 U4 (.A ( alucontrol[2] ) , .Y ( n1 ) ) ;
AND2X2 U3 (.A ( n23 ) , .B ( funct[5] ) , .Y ( n21 ) ) ;
FILL xofiller_FILL_1 () ;
FILL xofiller_FILL_2 () ;
OAI21X1 U16 (.A ( funct[0] ) , .B ( n13 ) , .C ( n14 ) , .Y ( n12 ) ) ;
NAND2X1 U15 (.A ( n4 ) , .B ( n12 ) , .Y ( n11 ) ) ;
OAI21X1 U14 (.A ( aluop[1] ) , .B ( aluop[0] ) , .C ( n11 ) 
    , .Y ( alucontrol[5] ) ) ;
OR2X1 U13 (.A ( n10 ) , .B ( n7 ) , .Y ( n9 ) ) ;
OAI21X1 U12 (.A ( n8 ) , .B ( n9 ) , .C ( n1 ) , .Y ( alucontrol[6] ) ) ;
INVX2 U11 (.A ( funct[0] ) , .Y ( n8 ) ) ;
INVX2 U10 (.A ( funct[1] ) , .Y ( n7 ) ) ;
INVX2 U9 (.A ( funct[2] ) , .Y ( n6 ) ) ;
OAI21X1 U24 (.A ( funct[0] ) , .B ( n20 ) , .C ( n17 ) , .Y ( alucontrol[2] ) ) ;
OAI21X1 U23 (.A ( funct[2] ) , .B ( n8 ) , .C ( n7 ) , .Y ( n19 ) ) ;
OAI22X1 U22 (.A ( aluop[1] ) , .B ( aluop[0] ) , .C ( n15 ) , .D ( n19 ) 
    , .Y ( alucontrol[3] ) ) ;
NAND3X1 U21 (.A ( funct[2] ) , .B ( n7 ) , .C ( funct[0] ) , .Y ( n14 ) ) ;
OAI21X1 U20 (.A ( funct[0] ) , .B ( n7 ) , .C ( n14 ) , .Y ( n18 ) ) ;
NAND2X1 U19 (.A ( aluop[1] ) , .B ( n18 ) , .Y ( n16 ) ) ;
OAI21X1 U18 (.A ( n15 ) , .B ( n16 ) , .C ( n17 ) , .Y ( alucontrol[4] ) ) ;
XNOR2X1 U17 (.B ( funct[1] ) , .Y ( n13 ) , .A ( n6 ) ) ;
NOR2X1 U32 (.A ( funct[4] ) , .B ( aluop[0] ) , .Y ( n23 ) ) ;
NOR2X1 U31 (.A ( n3 ) , .B ( n7 ) , .Y ( n22 ) ) ;
NAND3X1 U30 (.A ( n21 ) , .B ( n6 ) , .C ( n22 ) , .Y ( n20 ) ) ;
NOR2X1 U29 (.A ( n5 ) , .B ( n20 ) , .Y ( alucontrol[1] ) ) ;
NAND2X1 U28 (.A ( n21 ) , .B ( n5 ) , .Y ( n15 ) ) ;
NAND3X1 U27 (.A ( n4 ) , .B ( aluop[1] ) , .C ( funct[2] ) , .Y ( n10 ) ) ;
NAND2X1 U26 (.A ( n2 ) , .B ( n10 ) , .Y ( alucontrol[0] ) ) ;
AOI21X1 U25 (.A ( n3 ) , .B ( aluop[0] ) , .C ( alucontrol[1] ) , .Y ( n17 ) ) ;
FILL xofiller_FILL_3 () ;
FILL xofiller_FILL_4 () ;
FILL xofiller_FILL_5 () ;
FILL xofiller_FILL_6 () ;
FILL xofiller_FILL_7 () ;
FILL xofiller_FILL_8 () ;
FILL xofiller_FILL_9 () ;
FILL xofiller_FILL_10 () ;
FILL xofiller_FILL_11 () ;
FILL xofiller_FILL_12 () ;
FILL xofiller_FILL_13 () ;
FILL xofiller_FILL_14 () ;
FILL xofiller_FILL_15 () ;
FILL xofiller_FILL_16 () ;
FILL xofiller_FILL_17 () ;
FILL xofiller_FILL_18 () ;
FILL xofiller_FILL_19 () ;
FILL xofiller_FILL_20 () ;
FILL xofiller_FILL_21 () ;
FILL xofiller_FILL_22 () ;
FILL xofiller_FILL_23 () ;
FILL xofiller_FILL_24 () ;
FILL xofiller_FILL_25 () ;
FILL xofiller_FILL_26 () ;
FILL xofiller_FILL_27 () ;
endmodule


