# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/hany/ECE425/Lab08/lab08/lab08.cache/wt [current_project]
set_property parent.project_path /home/hany/ECE425/Lab08/lab08/lab08.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv /home/hany/ECE425/Lab08/sequential_examples/mips_fsm.sv
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top mips_fsm -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef mips_fsm.dcp

catch { report_utilization -file mips_fsm_utilization_synth.rpt -pb mips_fsm_utilization_synth.pb }
