//
// Milkyway Hierarchical Verilog Dump:
// Generated on 03/28/2017 at 12:39:37
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :counter_LIB
// Cell Name    :counter
// Hierarchy delimiter:'/'
// Write Command : write_verilog counter.pnr.v
//


module counter (data , load , up , clr , clk , Q );
input  [3:0] data ;
input  load ;
input  up ;
input  clr ;
input  clk ;
output [3:0] Q ;



DFFPOSX1 Q_reg_1_ (.Q ( Q[1] ) , .CLK ( clk ) , .D ( N14 ) ) ;
DFFPOSX1 Q_reg_0_ (.Q ( Q[0] ) , .CLK ( clk ) , .D ( N13 ) ) ;
OAI21X1 U8 (.A ( n6 ) , .B ( n7 ) , .C ( n8 ) , .Y ( N16 ) ) ;
INVX2 U7 (.A ( up ) , .Y ( n5 ) ) ;
INVX2 U6 (.A ( Q[0] ) , .Y ( n4 ) ) ;
INVX2 U5 (.A ( Q[1] ) , .Y ( n3 ) ) ;
INVX2 U4 (.A ( Q[2] ) , .Y ( n2 ) ) ;
INVX2 U3 (.A ( Q[3] ) , .Y ( n1 ) ) ;
DFFPOSX1 Q_reg_3_ (.Q ( Q[3] ) , .CLK ( clk ) , .D ( N16 ) ) ;
DFFPOSX1 Q_reg_2_ (.Q ( Q[2] ) , .CLK ( clk ) , .D ( N15 ) ) ;
NAND2X1 U16 (.A ( data[2] ) , .B ( load ) , .Y ( n17 ) ) ;
OAI21X1 U15 (.A ( n16 ) , .B ( n7 ) , .C ( n17 ) , .Y ( N15 ) ) ;
NAND2X1 U14 (.A ( Q[1] ) , .B ( n15 ) , .Y ( n13 ) ) ;
OAI21X1 U13 (.A ( n2 ) , .B ( n13 ) , .C ( n14 ) , .Y ( n9 ) ) ;
AOI22X1 U12 (.A ( Q[1] ) , .B ( n2 ) , .C ( Q[2] ) , .D ( n5 ) , .Y ( n11 ) ) ;
AOI21X1 U11 (.A ( n11 ) , .B ( n12 ) , .C ( n1 ) , .Y ( n10 ) ) ;
AOI21X1 U10 (.A ( n9 ) , .B ( n1 ) , .C ( n10 ) , .Y ( n6 ) ) ;
NAND2X1 U9 (.A ( load ) , .B ( data[3] ) , .Y ( n8 ) ) ;
NAND2X1 U24 (.A ( data[1] ) , .B ( load ) , .Y ( n23 ) ) ;
OAI21X1 U23 (.A ( n22 ) , .B ( n7 ) , .C ( n23 ) , .Y ( N14 ) ) ;
AOI22X1 U22 (.A ( n3 ) , .B ( Q[0] ) , .C ( n4 ) , .D ( up ) , .Y ( n12 ) ) ;
OAI21X1 U21 (.A ( up ) , .B ( n3 ) , .C ( n12 ) , .Y ( n18 ) ) ;
NAND2X1 U20 (.A ( n15 ) , .B ( n2 ) , .Y ( n20 ) ) ;
OR2X1 U19 (.A ( n21 ) , .B ( Q[2] ) , .Y ( n14 ) ) ;
OAI21X1 U18 (.A ( n3 ) , .B ( n20 ) , .C ( n14 ) , .Y ( n19 ) ) ;
AOI21X1 U17 (.A ( Q[2] ) , .B ( n18 ) , .C ( n19 ) , .Y ( n16 ) ) ;
OR2X1 U32 (.A ( load ) , .B ( clr ) , .Y ( n7 ) ) ;
NAND2X1 U31 (.A ( data[0] ) , .B ( load ) , .Y ( n26 ) ) ;
OAI21X1 U30 (.A ( Q[0] ) , .B ( n7 ) , .C ( n26 ) , .Y ( N13 ) ) ;
NOR2X1 U29 (.A ( n5 ) , .B ( n4 ) , .Y ( n15 ) ) ;
XNOR2X1 U28 (.B ( up ) , .Y ( n25 ) , .A ( Q[0] ) ) ;
NAND3X1 U27 (.A ( n3 ) , .B ( n5 ) , .C ( n4 ) , .Y ( n21 ) ) ;
OAI21X1 U26 (.A ( n25 ) , .B ( n3 ) , .C ( n21 ) , .Y ( n24 ) ) ;
AOI21X1 U25 (.A ( n15 ) , .B ( n3 ) , .C ( n24 ) , .Y ( n22 ) ) ;
endmodule


