//
// Milkyway Hierarchical Verilog Dump:
// Generated on 03/28/2017 at 14:48:48
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :mips_fsm_LIB
// Cell Name    :mips_fsm
// Hierarchy delimiter:'/'
// Write Command : write_verilog mips_fsm.pnr.v
//


module mips_fsm (op , alusrcb , pcsrc , reset , clk , irwrite , aluop , 
    regdst , regwrite , brnch , pcwrite , iord , memtoreg , alusrca , 
    memwrite );
input  [5:0] op ;
output [1:0] alusrcb ;
output [1:0] pcsrc ;
input  reset ;
input  clk ;
output [3:0] irwrite ;
output [1:0] aluop ;
output regdst ;
output regwrite ;
output brnch ;
output pcwrite ;
output iord ;
output memtoreg ;
output alusrca ;
output memwrite ;


wire [3:0] state ;
wire [3:0] next ;

assign aluop[0] = pcsrc[0] ;
assign brnch = pcsrc[0] ;
assign regdst = regwrite ;
INVX1 U1 (.A ( state[0] ) , .Y ( n1 ) ) ;
LATCH next_reg_0_ (.Q ( next[0] ) , .CLK ( N99 ) , .D ( n10 ) ) ;
DFFPOSX1 state_reg_0_ (.Q ( state[0] ) , .CLK ( clk ) , .D ( N25 ) ) ;
LATCH next_reg_3_ (.Q ( next[3] ) , .CLK ( N99 ) , .D ( n4 ) ) ;
DFFPOSX1 state_reg_3_ (.Q ( state[3] ) , .CLK ( clk ) , .D ( N28 ) ) ;
LATCH next_reg_2_ (.Q ( next[2] ) , .CLK ( N99 ) , .D ( N102 ) ) ;
DFFPOSX1 state_reg_2_ (.Q ( state[2] ) , .CLK ( clk ) , .D ( N27 ) ) ;
LATCH next_reg_1_ (.Q ( next[1] ) , .CLK ( N99 ) , .D ( N101 ) ) ;
DFFPOSX1 state_reg_1_ (.Q ( state[1] ) , .CLK ( clk ) , .D ( N26 ) ) ;
AND2X2 U3 (.A ( next[3] ) , .B ( n15 ) , .Y ( N28 ) ) ;
AND2X2 U4 (.A ( next[2] ) , .B ( n15 ) , .Y ( N27 ) ) ;
AND2X2 U5 (.A ( next[1] ) , .B ( n15 ) , .Y ( N26 ) ) ;
AND2X2 U6 (.A ( next[0] ) , .B ( n15 ) , .Y ( N25 ) ) ;
AND2X2 U7 (.A ( n41 ) , .B ( n42 ) , .Y ( n40 ) ) ;
INVX2 U8 (.A ( n25 ) , .Y ( pcsrc[1] ) ) ;
INVX2 U9 (.A ( irwrite[1] ) , .Y ( n2 ) ) ;
INVX2 U10 (.A ( n32 ) , .Y ( alusrca ) ) ;
INVX2 U11 (.A ( n36 ) , .Y ( n4 ) ) ;
INVX2 U12 (.A ( n28 ) , .Y ( n5 ) ) ;
INVX2 U13 (.A ( memwrite ) , .Y ( n6 ) ) ;
INVX2 U14 (.A ( n31 ) , .Y ( n7 ) ) ;
INVX2 U15 (.A ( n30 ) , .Y ( pcsrc[0] ) ) ;
INVX2 U16 (.A ( state[3] ) , .Y ( n9 ) ) ;
INVX2 U17 (.A ( n56 ) , .Y ( n10 ) ) ;
INVX2 U18 (.A ( n27 ) , .Y ( n11 ) ) ;
INVX2 U19 (.A ( state[1] ) , .Y ( n12 ) ) ;
INVX2 U21 (.A ( n52 ) , .Y ( n14 ) ) ;
INVX2 U22 (.A ( reset ) , .Y ( n15 ) ) ;
INVX2 U23 (.A ( n39 ) , .Y ( n16 ) ) ;
INVX2 U24 (.A ( op[5] ) , .Y ( n17 ) ) ;
INVX2 U25 (.A ( n35 ) , .Y ( n18 ) ) ;
INVX2 U26 (.A ( op[4] ) , .Y ( n19 ) ) ;
INVX2 U27 (.A ( op[3] ) , .Y ( n20 ) ) ;
INVX2 U28 (.A ( op[2] ) , .Y ( n21 ) ) ;
INVX2 U29 (.A ( op[1] ) , .Y ( n22 ) ) ;
INVX2 U30 (.A ( op[0] ) , .Y ( n23 ) ) ;
NOR2X1 U31 (.A ( n7 ) , .B ( n24 ) , .Y ( regwrite ) ) ;
NAND2X1 U32 (.A ( n25 ) , .B ( n26 ) , .Y ( pcwrite ) ) ;
NAND3X1 U33 (.A ( n27 ) , .B ( state[3] ) , .C ( state[2] ) , .Y ( n25 ) ) ;
NOR2X1 U34 (.A ( n28 ) , .B ( n29 ) , .Y ( memtoreg ) ) ;
NAND2X1 U35 (.A ( state[0] ) , .B ( state[1] ) , .Y ( n29 ) ) ;
NOR2X1 U36 (.A ( n1 ) , .B ( n26 ) , .Y ( irwrite[0] ) ) ;
OAI21X1 U37 (.A ( n24 ) , .B ( n28 ) , .C ( n6 ) , .Y ( iord ) ) ;
NOR2X1 U38 (.A ( n11 ) , .B ( n7 ) , .Y ( memwrite ) ) ;
NAND3X1 U39 (.A ( n31 ) , .B ( state[1] ) , .C ( state[0] ) , .Y ( n30 ) ) ;
OAI21X1 U40 (.A ( state[3] ) , .B ( n11 ) , .C ( n26 ) , .Y ( alusrcb[0] ) ) ;
NOR2X1 U41 (.A ( state[0] ) , .B ( state[1] ) , .Y ( n27 ) ) ;
OAI21X1 U42 (.A ( alusrcb[1] ) , .B ( n31 ) , .C ( state[0] ) , .Y ( n32 ) ) ;
NAND3X1 U43 (.A ( n33 ) , .B ( n34 ) , .C ( alusrcb[1] ) , .Y ( N99 ) ) ;
NAND3X1 U44 (.A ( n18 ) , .B ( n22 ) , .C ( op[5] ) , .Y ( n33 ) ) ;
AOI21X1 U45 (.A ( n37 ) , .B ( alusrcb[1] ) , .C ( aluop[1] ) , .Y ( n36 ) ) ;
NOR2X1 U46 (.A ( n38 ) , .B ( n7 ) , .Y ( aluop[1] ) ) ;
NOR2X1 U47 (.A ( n9 ) , .B ( state[2] ) , .Y ( n31 ) ) ;
OAI21X1 U48 (.A ( n39 ) , .B ( n1 ) , .C ( n34 ) , .Y ( n37 ) ) ;
OAI21X1 U49 (.A ( n22 ) , .B ( n21 ) , .C ( n14 ) , .Y ( n34 ) ) ;
OAI21X1 U50 (.A ( n1 ) , .B ( n2 ) , .C ( n40 ) , .Y ( N102 ) ) ;
NAND3X1 U51 (.A ( n43 ) , .B ( n1 ) , .C ( n5 ) , .Y ( n42 ) ) ;
OAI21X1 U52 (.A ( n44 ) , .B ( n45 ) , .C ( alusrcb[1] ) , .Y ( n41 ) ) ;
NOR2X1 U53 (.A ( n28 ) , .B ( state[1] ) , .Y ( alusrcb[1] ) ) ;
NAND2X1 U54 (.A ( state[2] ) , .B ( n9 ) , .Y ( n28 ) ) ;
OAI21X1 U55 (.A ( op[3] ) , .B ( n1 ) , .C ( n46 ) , .Y ( n45 ) ) ;
OAI21X1 U56 (.A ( op[2] ) , .B ( n17 ) , .C ( op[3] ) , .Y ( n46 ) ) ;
NAND3X1 U57 (.A ( n22 ) , .B ( n19 ) , .C ( n23 ) , .Y ( n44 ) ) ;
NOR2X1 U58 (.A ( n26 ) , .B ( n12 ) , .Y ( irwrite[1] ) ) ;
OR2X1 U59 (.A ( state[2] ) , .B ( state[3] ) , .Y ( n26 ) ) ;
OAI21X1 U60 (.A ( state[2] ) , .B ( n38 ) , .C ( n47 ) , .Y ( N101 ) ) ;
OAI21X1 U61 (.A ( n48 ) , .B ( n49 ) , .C ( n9 ) , .Y ( n47 ) ) ;
OAI21X1 U62 (.A ( n50 ) , .B ( n51 ) , .C ( n24 ) , .Y ( n49 ) ) ;
NAND2X1 U63 (.A ( state[1] ) , .B ( n1 ) , .Y ( n24 ) ) ;
NAND2X1 U64 (.A ( n14 ) , .B ( op[2] ) , .Y ( n51 ) ) ;
NAND3X1 U65 (.A ( n53 ) , .B ( n19 ) , .C ( n54 ) , .Y ( n52 ) ) ;
NOR2X1 U66 (.A ( op[3] ) , .B ( op[0] ) , .Y ( n54 ) ) ;
NOR2X1 U67 (.A ( state[0] ) , .B ( op[5] ) , .Y ( n53 ) ) ;
NAND2X1 U68 (.A ( state[2] ) , .B ( n22 ) , .Y ( n50 ) ) ;
NOR2X1 U69 (.A ( n16 ) , .B ( n38 ) , .Y ( n48 ) ) ;
NAND3X1 U70 (.A ( op[3] ) , .B ( op[5] ) , .C ( n55 ) , .Y ( n39 ) ) ;
NOR2X1 U71 (.A ( op[1] ) , .B ( n35 ) , .Y ( n55 ) ) ;
NAND2X1 U72 (.A ( state[0] ) , .B ( n12 ) , .Y ( n38 ) ) ;
OAI21X1 U73 (.A ( n57 ) , .B ( n58 ) , .C ( n59 ) , .Y ( n56 ) ) ;
NOR2X1 U74 (.A ( state[3] ) , .B ( state[0] ) , .Y ( n59 ) ) ;
OR2X1 U75 (.A ( n43 ) , .B ( n35 ) , .Y ( n58 ) ) ;
NAND3X1 U76 (.A ( n21 ) , .B ( n19 ) , .C ( n23 ) , .Y ( n35 ) ) ;
NAND2X1 U77 (.A ( n12 ) , .B ( n17 ) , .Y ( n43 ) ) ;
NAND3X1 U78 (.A ( state[2] ) , .B ( n20 ) , .C ( op[1] ) , .Y ( n57 ) ) ;
assign irwrite[3] = 1'b0;
assign irwrite[2] = 1'b0;
endmodule


